// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FTOptix.RAEtherNetIP;
using FTOptix.CommunicationDriver;
using FTOptix.NativeUI;
namespace FeaturesDemo2
{
    public partial class CookieQuality
    {
        /// <summary>
        /// model input class for CookieQuality.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(1)]
            [ColumnName(@"Diameter")]
            public float Diameter { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"Exit_Temperature")]
            public float Exit_Temperature { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"Height")]
            public float Height { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"Quality_Index")]
            public float Quality_Index { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for CookieQuality.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Diameter")]
            public float Diameter { get; set; }

            [ColumnName(@"Exit_Temperature")]
            public float Exit_Temperature { get; set; }

            [ColumnName(@"Height")]
            public float Height { get; set; }

            [ColumnName(@"Quality_Index")]
            public float Quality_Index { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        public static string MLNetModelPath { get; set; }

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
